# -*- coding: utf-8 -*-
"""데이터 전처리

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjpem8-ZAiBeh58QRRfVpu05p4HD0LgR
"""

!python3 -m pip install -U "yt-dlp[default]"

# https://www.youtube.com/watch?v=fwWxnvgBYlo 영상을 다운로드
!yt-dlp https://www.youtube.com/watch?v=fwWxnvgBYlo -f 'bv' \
--download-sections "*04:03:54-4:20:00" \
-o "video.mp4" -S "codec:h264"

!ls

# 리플레이에서 미니맵 부분만 잘라냄
!ffmpeg -i video.mp4 -vf "crop=280:280:in_w-290:in_h-290" t1_geng_cropped_mp4_280px.mp4

# 미니맵 영상을 프레임단위로 이미지로 분해
# 저장 폴더 생성
!mkdir -p frames

!ffmpeg -i t1_geng_cropped_mp4_280px.mp4 \
-vf "fps=1/2" \
-q:v 2 \
frames/frame_%05d.png

# fps=1/2 : 2초당 1프레임 추출 (0.5fps)
# -q:v 2 : 프레임 이미지 품질 설정 (1이 최고, 31이 최저 품질)
# frames/frame_%05d.png : 'frame_00001.png', 'frame_00002.png'처럼 순차적으로 저장

!ls

# 프레임으로 분할된 이미지 리스트 확인
import os
images = os.listdir('frames')

from IPython.display import Image

Image(filename='frames/frame_00001.png')

from huggingface_hub import login

login(token="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")

# 이미지를 huggingface_dataset으로 저장
from huggingface_hub import upload_folder

upload_folder(
    repo_id='namepen/20250524_buildwithai_tutorial', # 실제로 할때는 beomi대신 개개인 아이디 사용하기!
    repo_type="dataset",
    folder_path="frames",  # path to your local folder
    path_in_repo="",       # upload to the root of the dataset repo
    commit_message="Initial upload of frames",
)

# 이미지를 google drive 폴더로 전달
!cp -r frames "drive/MyDrive/[Build with AI] 적정글 예측/frames"